### ISSUE TITLE
XSS in stripHtml

### ISSUE THREAD

**Issue by mayorovp** [chabanovsky/so_association_tools#11]
Try call `stripHtml("<img onerror='alert(\"XSS!\")' src=bogus>")`

Source: https://stackoverflow.com/questions/822452/strip-html-from-text-javascript#comment9107196_822486

**Comment by chabanovsky** [comment]
Thank you! I fixed this issue with the solution suggested in the same question: https://stackoverflow.com/a/822464/564240
