### ISSUE TITLE
On request "api/get-answers" server return 500 error

### ISSUE THREAD

**Issue by urffin** [chabanovsky/so_association_tools#4]
Request URL:http://demo.chabanovsky.com/api/get-answers/?ids=184629;184633;184635;184637;184638;184639;184649;184656;184670;184672;184673;184682;184696;184701;184720;184728;184734;184746;184755;184795;184807;184835;184854;184885;184924;184949;184971;184986;185011;185016;185031;185053;185062;185070;185106;185115;185156;185165;185169;185181;185196;185201;185215;185246;185308;185550;185564;185576;185603;185712;185720;185789;185803;185846;185853;185877;185971;185979;185989;185990;186140;186286;186309;186395;186434;186457;186579;186967;186988;187163;187183;187215;187223;187405;187549;187565;187599;188042;188063;188100;188413;189279;189302;189312;189503;189551;189713;189732;189740;189748;189858;189859;189862;189938;190046;190139;190535;190866;190869;191005;191049;191525;191918;192010;192040;192098;192155;192823;193577;193705;194065;194269;194372;194393;194433;194475;194506;194720;194743;195155;195187;195196;195198;195199;195418;195432;195705;196132;196782;196886;196919;196934;197847;197874;197879;199806;200024;200038;200154;203901;204187;204235;208240;210422;215166;216127;216139;216159;216744;216943;216948;217681;217939;222164;222193;224671;225428;235510;236424;237886;240292;240381;240498;250413;265313;271471;309983;310251;311113;312203;315112;316042;316112;316233;331424;331525;334450;334499;334507;334568;335079;335114;339377;344863;344907;348483;350893;354692;360696;368692;368709;375554;377591;377894;378918;378932;378987;379021;379627;379687;381386;381392;381499;381523;381524;381599;383547;385765;385771;386201;389723;400182;400187;400211;400230;417196;431717;431722;431726;449493;482129;482177;482189;488642;488651;496175;499983;502932;502985;502993;503002;503012;503186;503215;504832;505122;505344;508563;508818;515402;515419;515593;515605;519734;522655;538091;538175;544238;544337;549611;549644;577663;614031;614792;615022;615028;615049;615795;615845;615872;615887;615901;615910;615989;616013;616053;616101;616122;616281;616523;616551;618817;618828;618976;621591;626983;628776;638670;645024;647713;648822;648866;649920;649924;657831;657879;657888;675779;676374;686583;686915;687811;687856;687907;687969;688017;688088;694615;694644;694652;706648;713861;713871;713872;714566;717461;717501;720857;720865;720902;720905;720983;721029;721065;721091;721797;721922;726186;735896;735928;736035;736044;736049;736097;736113;736116;736167;740552;740603;750386;750440;750454;750707;753350;753413;753637;756621;764798;765147;765149;765216;765375;765387;765908;765935;765942;765965;765967;766018;766037;766044;766097;766105;766133;766208;766217;766270;766324;766328;766333;766363;766537;766552;766553;766554;766602;766630;766631;766668;766696;766708;766741;766766;766843;766877;766878;766895;766907;766920;766930;766933;766949;767004;767282;767341;767642;767750;767937;768021;768023;768096;768097;768172;768386;768393;768440;768624;768714;768732;769046;769077;769083;769201;769278;769428;769443;769447;769468;769590;769805;769869;769893;769949;770022;770351;770788;770924;771666;771803;771804;771828;771851;771927;771974;772078;772132;772430;772445;776351;776364;776445;776486;776518;776595;776698;776715;776808;776957;776959;776973;777244;777655;777805;777822;778161;778254;778275;778286;778615;778722;778895;778975;778993;779128;779317;779681;779818;779830;779856;779874;779899;779948;779987;779993;779999;780060;780103;780234;780267;780286;780312;780361;780566;780804;781187;781356;781433;781860;782168;782202;782502;782521;782524;782529;782806;783107;783174;783220;783289;783368;783793;783935;784001;784055;784725;784955;785220;785272;785328;785345;786255;786495;786818;787238;787243;787301;788086;788223;788577;788609;789811;792783;792901;792982;794252;794891;796400;796746&site=stackoverflow
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:5.9.6.228:80

**Comment by chabanovsky** [comment]
Fixed. The url was to long to process on SE side. Now we are requesting not more then first 10 answers.
