### ISSUE TITLE
Improvement: Find association targets by URL

### ISSUE THREAD

**Issue by nofate** [chabanovsky/so_association_tools#5]
_"Suggested"_ tab requires user to paste EN.SO question URL as a left side for association. 

Further it asks user to search for some RU.SO question as a right side of this association. Since search results quality is quite questionable (search by full question title does not return relevant result), I suggest to allow lookup by RU.SO question URL too.

**Comment by chabanovsky** [comment]
Theoretically, there should not be use cases for it. If one knows an en-ru pair, why they don't just add it directly through a comment on SOru? Could you please tell a few use cases for the feature?

**Comment by chabanovsky** [comment]
Done. Now a user can put an url of a SOru question to the search box and it will be uploaded as a search result.
